### ISSUE TITLE
error in connecting to MITRE's CTI TAXII server when convert yaml to json

### ISSUE THREAD

**Issue by yux1a0** [rabobank-cdc/DeTTECT#104]
error in connecting to MITRE's CTI TAXII server when convert yaml to json

```
root@3d64ce686607:~/DeTTECT# python3 dettect.py ds -fd data-sources-new\ \(1\).yaml -l
[!] Cannot connect to MITRE's CTI TAXII server: https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/
```

<img width="1062" alt="image" src="https://github.com/rabobank-cdc/DeTTECT/assets/49915226/cb168ced-2673-4c9d-828b-d020573bfef5">

**Comment by rubinatorz** [comment]
hi @yux1a0 

That means that the TAXII server from MITRE is not reachable and we as DTT&CT devs can't fix that.

If you want to proceed, check out the --local-stix-path CLI parameter. You can clone the CTI STIX repository offline (https://github.com/mitre/cti) and use it in DeTT&CT as offline ATT&CK source instead of the TAXII server.
