### ISSUE TITLE
Cannot connect to MITRE's CTI TAXII server

### ISSUE THREAD

**Issue by ferezito** [rabobank-cdc/DeTTECT#105]
Hi.

When I execute next command, the output is: `[!] Cannot connect to MITRE's CTI TAXII server: https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/`

Can you resolve? Thanks

**Comment by rubinatorz** [comment]
Hi @ferezito 

That means that the TAXII server from MITRE is not reachable and we as DeTT&CT devs can't fix that.

If you want to proceed, check out the --local-stix-path CLI parameter. You can clone the CTI STIX repository offline (https://github.com/mitre/cti) and use it in DeTT&CT as offline ATT&CK source instead of the TAXII server.
