### ISSUE TITLE
Unable to connect to Mitre Taxii Server

### ISSUE THREAD

**Issue by etheruler** [rabobank-cdc/DeTTECT#106]
Hello - I've been exploring DeTTECT for the past month or so, and today  I am having an issue when I create a JSON file from my yaml file.   This is the 1st time using DeTTECT since the new Mitre ATT&CK 14 release.

        __[!] Cannot connect to MITRE's CTI TAXII server: https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/

I tried pinging cti-taxii.mitre.org and that domain is not responding.

Thank You

**Comment by etheruler** [comment]
Never mind is seems to be working now.   Thanks

**Comment by rubinatorz** [comment]
MITRE's TAXII server was down for a couple of days. They indeed just fixed this.

If you encounter this in the future again, check out the --local-stix-path CLI parameter. You can clone the CTI STIX repository offline (https://github.com/mitre/cti) and use it in DeTT&CT as offline ATT&CK source instead of the TAXII server.
