### ISSUE TITLE
Error in getting data from MITRE TAXII Server

### ISSUE THREAD

**Issue by BriPwn** [rabobank-cdc/DeTTECT#122]
Looks like Mitre moved to a new TAXII server. I'm getting an error when running detect.py generic -ds

[!] Cannot connect to MITRE's CTI TAXII server: https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/

**Comment by rubinatorz** [comment]
Hi @BriPwn 

The SSL certificate of MITRE's TAXII server is expired.

You can try to use the local-stix-path command line option. That's faster and more stable too. 

Regards
Ruben

**Comment by ruale7** [comment]
Hi all,

I am getting the same error when I execut "python dettect.py g -g all" to get the threat actor heatmap. How can I use the local-stix-path argument to avoid this error and get the json?

Thanks.

Regards.

**Comment by ruale7** [comment]
Hi all,

I am getting the same error when I execute "python dettect.py g -g all" to get the threat actor heatmap. How can I use the local-stix-path argument to avoid this error and get the json? Could the code be modified to ignore the SSL certificate when the request is done?

Thanks.

Regards.

**Comment by ruale7** [comment]
Hi again,

I am trying to execute dettect.py using the local-stix-path: >python dettect.py d -ft ../../2_Mitre_Coverage.yaml -l --local-stix-path "C:\Users\cti-master\cti-master" and I am getting the following error:

  File "C:\Users\aruizheras\Deloitte (O365D)\[ECC] Detect & Respond - [Team] Threat Modeling - [Team] Threat Modeling\4. Threat Monitoring Security Posture Reports\2024.11 - CIC-FI Kone\1. Internal\DeTTECT\DeTTECT\generic.py", line 123, in load_attack_data
    mitre = attack_client(local_path=local_stix_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attack_client.__init__() got an unexpected keyword argument 'local_path'

Does anyone know how to solve it?

Thanks,

Regards.

**Comment by ruale7** [comment]
Hi again,

I am trying to execute dettect.py using the local-stix-path: >python dettect.py d -ft ../../2_Mitre_Coverage.yaml -l --local-stix-path "C:\Users\cti-master\cti-master" and I am getting the following error:

TypeError: attack_client.init() got an unexpected keyword argument 'local_path'

Does anyone know how to solve it?

Thanks,

Regards.

**Comment by rubinatorz** [comment]
hi @ruale7 

Ignoring the SSL certificate warning is not something I would like to do. If the certificate is not correct, it's not correct. This time it's an expired certificate, but next time there could be an adversary-in-the-middle attack. I don't want to be responsible for this.

Using the local-stix-path is a good option anyway because it's faster and more stable. To do so, git clone the https://github.com/mitre/cti.git repository in some path on your machine. And use --local-stix-path path_to_that_folder option in DeTT&CT.

You've already found that part I see. The errormessage on "local_path" is remarkable. Can you check the attackcti library version (pip list)?

PS you might consider removing some (sensitive) parts of your local paths in the error you've sent.

**Comment by ruale7** [comment]
Hi @rubinatorz,

Thank you for the response. The version of attackcti is 0.4.4. Is this version working for you?

Regards.

**Comment by rubinatorz** [comment]
Hi @ruale7 

In the requirements.txt file we refer to attackcti==0.3.8 because the in a newer version it changed the local_path to local_paths. DeTT&CT is not yet compatible with the newer versions.

If you `pip install -r requirements.txt` or just `pip install attackcti==0.3.8` it should work.

**Comment by ruale7** [comment]
Hi @rubinatorz,

Thanks! It works.

Regards.
